### ISSUE TITLE
Slide 11: Text is not appearing

### ISSUE THREAD

**Issue by lizdumont** [Datapolitan-Training/intro-data-vis-excel#9]
@datapolitan can you figure out what's wrong with the code on Slide 11 that's causing the bracket to appear and the text to be so small?

**Comment by datapolitan** [comment]
closed with commit c6a0bf70a43eb46fc2c2454570c3cb9597b58296

**Comment by datapolitan** [comment]
A few things @lizdumont:
+ Without a bullet or `#`, the text defaults to `<p>`, which is small text
+ There were brackets around the image, but no link, so the brackets were displayed
+ The image needed to be resized so all of it could be displayed.
